version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - CI=true npm test
  build:
    commands:
      - npm run-script build
      # Deploy to prod
      - aws s3 sync --content-type "text/html" --exclude "*" --include "*.html" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "text/css" --exclude "*" --include "*.css" --include "*.css.map" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "text/javascript" --exclude "*" --include "*.js" --include "*.js.map" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "application/json" --exclude "*" --include "*.json" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "image/x-icon" --exclude "*" --include "*.ico" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "image/svg+xml" --exclude "*" --include "*.svg" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "image/png" --exclude "*" --include "*.png" --delete build/ s3://csfrx.com/
      - aws s3 sync --content-type "image/jpeg" --exclude "*" --include "*.jpg" --delete build/ s3://csfrx.com/

      # Use AWS SAM to package the application using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json
